# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



Politician.create(name: "Jeff Sessions", party: "R", state: "Alabama", multiplier: 9, image: "http://vote-usa.org/Image.aspx?Id=ALSessionsJeff&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Richard Shelby", party: "R", state: "Alabama", multiplier: 9, image: "http://vote-usa.org/Image.aspx?Id=ALShelbyRichardC&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Lisa Murkowski", party: "R", state: "Alaska", multiplier: 3, image: "http://vote-usa.org/Image.aspx?Id=AKMurkowskiLisa&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Dan Sullivan", party: "R", state: "Alaska", multiplier: 3, image: "http://vote-usa.org/Image.aspx?Id=AKSullivanDan&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Jeff Flake", party: "R", state: "Arizona", multiplier: 11, image: "http://vote-usa.org/Image.aspx?Id=AZFlakeJeff&Col=Headshot100&Def=Headshot100")
Politician.create(name: "John McCain", party: "R", state: "Arizona", multiplier: 11, image: "http://vote-usa.org/Image.aspx?Id=AZMccainJohn&Col=Headshot100&Def=Headshot100")
Politician.create(name: "John Boozman", party: "R", state: "Arkansas", multiplier: 6, image: "http://vote-usa.org/Image.aspx?Id=ARBoozmanJohn&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Thomas B. Cotton", party: "R", state: "Arkansas", multiplier: 6, image: "http://vote-usa.org/Image.aspx?Id=ARCottonThomasB&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Dianne Feinstein", party: "D", state: "California", multiplier: 55, image: "http://vote-usa.org/Image.aspx?Id=CAFeinsteinDianne&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Kamala D. Harris", party: "D", state: "California", multiplier: 55, image: "http://vote-usa.org/Image.aspx?Id=CAHarrisKamalaD&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Michael Bennet", party: "D", state: "Colorado", multiplier: 9, image: "http://vote-usa.org/Image.aspx?Id=COBennetMichaelF&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Cory Gardner", party: "R", state: "Colorado", multiplier: 9, image: "http://vote-usa.org/Image.aspx?Id=COGardnerCory&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Richard Blumenthal", party: "D", state: "Connecticut", multiplier: 7, image: "http://vote-usa.org/Image.aspx?Id=CTBlumenthalRichard&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Christopher S. Murphy", party: "D", state: "Connecticut", multiplier: 7, image: "http://vote-usa.org/Image.aspx?Id=CTMurphyChristopherS&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Thomas Carper", party: "D", state: "Delaware", multiplier: 3, image: "http://vote-usa.org/Image.aspx?Id=DECarperThomasR&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Christopher Coons", party: "D", state: "Delaware", multiplier: 3, image: "http://vote-usa.org/Image.aspx?Id=DECoonsChristopherA&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Bill Nelson", party: "D", state: "Florida", multiplier: 29, image: "http://vote-usa.org/Image.aspx?Id=FLNelsonBill&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Marco Rubio", party: "R", state: "Florida", multiplier: 29, image: "http://vote-usa.org/Image.aspx?Id=FLRubioMarco&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Johnny Isakson", party: "R", state: "Georgia", multiplier: 16, image: "http://vote-usa.org/Image.aspx?Id=GAIsaksonJohnny&Col=Headshot100&Def=Headshot100")
Politician.create(name: "David Alfred Perdue", party: "R", state: "Georgia", multiplier: 16, image: "http://vote-usa.org/Image.aspx?Id=GAPerdueDavidAlfred&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Mazie K. Hirono", party: "D", state: "Hawaii", multiplier: 4, image: "http://vote-usa.org/Image.aspx?Id=HIHironoMazieK&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Brian Schatz", party: "D", state: "Hawaii", multiplier: 4, image: "http://vote-usa.org/Image.aspx?Id=HISchatzBrian&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Mike Crapo", party: "R", state: "Idaho", multiplier: 4, image: "http://vote-usa.org/Image.aspx?Id=IDCrapoMichaelD&Col=Headshot100&Def=Headshot100")
Politician.create(name: "James Risch", party: "R", state: "Idaho", multiplier: 4, image: "http://vote-usa.org/Image.aspx?Id=IDRischJamesE&Col=Headshot100&Def=Headshot100")
Politician.create(name: "L. Tammy Duckworth", party: "D", state: "Illinois", multiplier: 20, image: "http://vote-usa.org/Image.aspx?Id=ILDuckworthLTammy&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Richard Durbin", party: "D", state: "Illinois", multiplier: 20, image: "http://vote-usa.org/Image.aspx?Id=ILDurbinRichardJ&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Joe Donnelly", party: "D", state: "Indiana", multiplier: 11, image: "http://vote-usa.org/Image.aspx?Id=INDonnellyJoe&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Todd Young", party: "R", state: "Indiana", multiplier: 11, image: "http://vote-usa.org/Image.aspx?Id=INYoungTodd&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Joni K. Ernst", party: "R", state: "Iowa", multiplier: 6, image: "http://vote-usa.org/Image.aspx?Id=IAErnstJoni&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Chuck Grassley", party: "R", state: "Iowa", multiplier: 6, image: "http://vote-usa.org/Image.aspx?Id=IAGrassleyChuckE&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Jerry Moran", party: "R", state: "Kansas", multiplier: 6, image: "http://vote-usa.org/Image.aspx?Id=KSMoranJerry&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Pat Roberts", party: "R", state: "Kansas", multiplier: 6, image: "http://vote-usa.org/Image.aspx?Id=KSRobertsPat&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Mitch McConnell", party: "R", state: "Kentucky", multiplier: 8, image: "http://vote-usa.org/Image.aspx?Id=KYMcconnellMitch&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Rand Paul", party: "R", state: "Kentucky", multiplier: 8, image: "http://vote-usa.org/Image.aspx?Id=KYPaulRand&Col=Headshot100&Def=Headshot100")
Politician.create(name: "William Bill Cassidy", party: "R", state: "Louisiana", multiplier: 8, image: "http://vote-usa.org/Image.aspx?Id=LACassidyBill&Col=Headshot100&Def=Headshot100")
Politician.create(name: "John Kennedy", party: "R", state: "Louisiana", multiplier: 8, image: "http://vote-usa.org/Image.aspx?Id=LAKennedyJohn&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Susan Collins", party: "R", state: "Maine", multiplier: 4, image: "http://vote-usa.org/Image.aspx?Id=MECollinsSusanM&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Angus King", party: "I", state: "Maine", multiplier: 4, image: "http://vote-usa.org/Image.aspx?Id=MEKingAngus&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Benjamin Cardin", party: "D", state: "Maryland", multiplier: 10, image: "http://vote-usa.org/Image.aspx?Id=MDCardinBenjaminL&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Chris Van Hollen", party: "D", state: "Maryland", multiplier: 10, image: "http://vote-usa.org/Image.aspx?Id=MDVanhollenChris&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Edward J. Markey", party: "D", state: "Massachusetts", multiplier: 11, image: "http://vote-usa.org/Image.aspx?Id=MAMarkeyEdwardJ&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Elizabeth A. Warren", party: "D", state: "Massachusetts", multiplier: 11, image: "http://vote-usa.org/Image.aspx?Id=MAWarrenElizabethA&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Gary Peters", party: "D", state: "Michigan", multiplier: 16, image: "http://vote-usa.org/Image.aspx?Id=MIPetersGary&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Debbie Stabenow", party: "D", state: "Michigan", multiplier: 16, image: "http://vote-usa.org/Image.aspx?Id=MIStabenowDebbie&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Al Franken", party: "D", state: "Minnesota", multiplier: 10, image: "http://vote-usa.org/Image.aspx?Id=MNFrankenAl&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Amy Klobuchar", party: "D", state: "Minnesota", multiplier: 10, image: "http://vote-usa.org/Image.aspx?Id=MNKlobucharAmy&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Thad Cochran", party: "R", state: "Mississippi", multiplier: 6, image: "http://vote-usa.org/Image.aspx?Id=MSCochranThad&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Roger Wicker", party: "R", state: "Mississippi", multiplier: 6, image: "http://vote-usa.org/Image.aspx?Id=MSWickerRogerF&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Roy Blunt", party: "R", state: "Missouri", multiplier: 10, image: "http://vote-usa.org/Image.aspx?Id=MOBluntRoy&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Claire McCaskill", party: "D", state: "Missouri", multiplier: 10, image: "http://vote-usa.org/Image.aspx?Id=MOMccaskillClaire&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Steve Daines", party: "R", state: "Montana", multiplier: 3, image: "http://vote-usa.org/Image.aspx?Id=MTDainesSteve&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Jon Tester", party: "D", state: "Montana", multiplier: 3, image: "http://vote-usa.org/Image.aspx?Id=MTTesterJon&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Deb Fischer", party: "R", state: "Nebraska", multiplier: 5, image: "http://vote-usa.org/Image.aspx?Id=NEFischerDeb&Col=Headshot100&Def=Headshot100")
Politician.create(name: "Ben Sasse", party: "R", state: "Nebraska", multiplier: 5, image: "http://vote-usa.org/Image.aspx?Id=NESasseBen&Col=Headshot100&Def=Headshot100")
Politician.create(name: "John Barrasso", party: "R", multiplier: 3, image: "http://vote-usa.org/Image.aspx?Id=WYBarrassoJohn&Col=Headshot100&Def=Headshot100", state: "Wyoming")
Politician.create(name: "Mike Enzi", party: "R", multiplier: 3, image: "http://vote-usa.org/Image.aspx?Id=WYEnziMichaelB&Col=Headshot100&Def=Headshot100", state: "Wyoming")
Politician.create(name: "Tammy Baldwin", party: "D", multiplier: 10, image: "http://vote-usa.org/Image.aspx?Id=WIBaldwinTammy&Col=Headshot100&Def=Headshot100", state: "Wisconsin")
Politician.create(name: "Ron Johnson", party: "R", multiplier: 10, image: "http://vote-usa.org/Image.aspx?Id=WIJohnsonRon&Col=Headshot100&Def=Headshot100", state: "Wisconsin")
Politician.create(name: "Shelley Moore Capito", party: "R", multiplier: 5, image: "http://vote-usa.org/Image.aspx?Id=WVCapitoShelleyMoore&Col=Headshot100&Def=Headshot100", state: "West Virginia")
Politician.create(name: "Joe Manchin, III", party: "D", multiplier: 5, image: "http://vote-usa.org/Image.aspx?Id=WVManchinJoeIii&Col=Headshot100&Def=Headshot100", state: "West Virginia")
Politician.create(name: "Maria Cantwell", party: "D", multiplier: 8, image: "http://vote-usa.org/Image.aspx?Id=WACantwellMaria&Col=Headshot100&Def=Headshot100", state: "Washington")
Politician.create(name: "Patty Murray", party: "D", multiplier: 8, image: "http://vote-usa.org/Image.aspx?Id=WAMurrayPatty&Col=Headshot100&Def=Headshot100", state: "Washington")
Politician.create(name: "Timothy M. Kaine", party: "D", multiplier: 13, image: "http://vote-usa.org/Image.aspx?Id=VAKaineTimothyM&Col=Headshot100&Def=Headshot100", state: "Virginia")
Politician.create(name: "Mark Warner", party: "D", multiplier: 13, image: "http://vote-usa.org/Image.aspx?Id=VAWarnerMarkR&Col=Headshot100&Def=Headshot100", state: "Virginia")
Politician.create(name: "Patrick Leahy", party: "D", multiplier: 3, image: "http://vote-usa.org/Image.aspx?Id=VTLeahyPatrickJ&Col=Headshot100&Def=Headshot100", state: "Vermont")
Politician.create(name: "Bernie Sanders", party: "D", multiplier: 3, image: "http://vote-usa.org/Image.aspx?Id=VTSandersBernard&Col=Headshot100&Def=Headshot100", state: "Vermont")
Politician.create(name: "Orrin Hatch", party: "R", multiplier: 6, image: "http://vote-usa.org/Image.aspx?Id=UTHatchOrrinG&Col=Headshot100&Def=Headshot100", state: "Utah")
Politician.create(name: "Mike Lee", party: "R", multiplier: 6, image: "http://vote-usa.org/Image.aspx?Id=UTLeeMike&Col=Headshot100&Def=Headshot100", state: "Utah")
Politician.create(name: "John Cornyn", party: "R", multiplier: 36, image: "http://vote-usa.org/Image.aspx?Id=TXCornynJohn&Col=Headshot100&Def=Headshot100", state: "Texas")
Politician.create(name: "Ted Cruz", party: "R", multiplier: 36, image: "http://vote-usa.org/Image.aspx?Id=TXCruzTed&Col=Headshot100&Def=Headshot100", state: "Texas")
Politician.create(name: "Lamar Alexander", party: "R", multiplier: 11, image: "http://vote-usa.org/Image.aspx?Id=TNAlexanderLamar&Col=Headshot100&Def=Headshot100", state: "Tennessee")
Politician.create(name: "Bob Corker", party: "R", multiplier: 11, image: "http://vote-usa.org/Image.aspx?Id=TNCorkerBob&Col=Headshot100&Def=Headshot100", state: "Tennessee")
Politician.create(name: "Mike Rounds", party: "R", multiplier: 3, image: "http://vote-usa.org/Image.aspx?Id=SDRoundsMikeA&Col=Headshot100&Def=Headshot100", state: "South Dakota")
Politician.create(name: "John R. Thune", party: "R", multiplier: 3, image: "http://vote-usa.org/Image.aspx?Id=SDThuneJohnR&Col=Headshot100&Def=Headshot100", state: "South Dakota")
Politician.create(name: "Lindsey Graham", party: "R", multiplier: 9, image: "http://vote-usa.org/Image.aspx?Id=SCGrahamLindseyO&Col=Headshot100&Def=Headshot100", state: "South Carolina")
Politician.create(name: "Tim Scott", party: "R", multiplier: 9, image: "http://vote-usa.org/Image.aspx?Id=SCScottTim&Col=Headshot100&Def=Headshot100", state: "South Carolina")
Politician.create(name: "Jack Reed", party: "D", multiplier: 4, image: "http://vote-usa.org/Image.aspx?Id=RIReedJackF&Col=Headshot100&Def=Headshot100", state: "Rhode Island")
Politician.create(name: "Sheldon Whitehouse", party: "D", multiplier: 4, image: "http://vote-usa.org/Image.aspx?Id=RIWhitehouseSheldon&Col=Headshot100&Def=Headshot100", state: "Rhode Island")
Politician.create(name: "Bob Casey, Jr.", party: "D", multiplier: 20, image: "http://vote-usa.org/Image.aspx?Id=PACaseyBobJR&Col=Headshot100&Def=Headshot100", state: "Pennsylvania")
Politician.create(name: "Patrick Toomey", party: "R", multiplier: 20, image: "http://vote-usa.org/Image.aspx?Id=PAToomeyPatrickJ&Col=Headshot100&Def=Headshot100", state: "Pennsylvania")
Politician.create(name: "Jeff Merkley", party: "D", multiplier: 7, image: "http://vote-usa.org/Image.aspx?Id=ORMerkleyJeff&Col=Headshot100&Def=Headshot100", state: "Oregon")
Politician.create(name: "Ron Wyden", party: "D", multiplier: 7, image: "http://vote-usa.org/Image.aspx?Id=ORWydenRon&Col=Headshot100&Def=Headshot100", state: "Oregon")
Politician.create(name: "Jim Inhofe", party: "R", multiplier: 7, image: "http://vote-usa.org/Image.aspx?Id=OKInhofeJimM&Col=Headshot100&Def=Headshot100", state: "Oklahoma")
Politician.create(name: "James Lankford", party: "R", multiplier: 7, image: "http://vote-usa.org/Image.aspx?Id=OKLankfordJames&Col=Headshot100&Def=Headshot100", state: "Oklahoma")
Politician.create(name: "Sherrod Brown", party: "D", multiplier: 18, image: "http://vote-usa.org/Image.aspx?Id=OHBrownSherrodCampbell&Col=Headshot100&Def=Headshot100", state: "Ohio")
Politician.create(name: "Rob Portman", party: "R", multiplier: 18, image: "http://vote-usa.org/Image.aspx?Id=OHPortmanRob&Col=Headshot100&Def=Headshot100", state: "Ohio")
Politician.create(name: "Heidi Heitkamp", party: "D", multiplier: 3, image: "http://vote-usa.org/Image.aspx?Id=NDHeitkampHeidi&Col=Headshot100&Def=Headshot100", state: "North Dakota")
Politician.create(name: "John Hoeven", party: "R", multiplier: 3, image: "http://vote-usa.org/Image.aspx?Id=NDHoevenJohn&Col=Headshot100&Def=Headshot100", state: "North Dakota")
Politician.create(name: "Richard Burr", party: "R", multiplier: 15, image: "http://vote-usa.org/Image.aspx?Id=NCBurrRichard&Col=Headshot100&Def=Headshot100", state: "North Carolina")
Politician.create(name: "Tom Tillis", party: "R", multiplier: 15, image: "http://vote-usa.org/Image.aspx?Id=NCTillisThom&Col=Headshot100&Def=Headshot100", state: "North Carolina")
Politician.create(name: "Kirsten Gillibrand", party: "D", multiplier: 29, image: "http://vote-usa.org/Image.aspx?Id=NYGillibrandKirstenE&Col=Headshot100&Def=Headshot100", state: "New York")
Politician.create(name: "Chuck Schumer", party: "D", multiplier: 29, image: "http://vote-usa.org/Image.aspx?Id=NYSchumerCharlesE&Col=Headshot100&Def=Headshot100", state: "New York")
Politician.create(name: "Martin T. Heinrich", party: "D", multiplier: 5, image: "http://vote-usa.org/Image.aspx?Id=NMHeinrichMartinT&Col=Headshot100&Def=Headshot100", state: "New Mexico")
Politician.create(name: "Tom Udall", party: "D", multiplier: 5, image: "http://vote-usa.org/Image.aspx?Id=NMUdallTom&Col=Headshot100&Def=Headshot100", state: "New Mexico")
Politician.create(name: "Cory Booker", party: "D", multiplier: 14, image: "http://vote-usa.org/Image.aspx?Id=NJBookerCory&Col=Headshot100&Def=Headshot100", state: "New Jersey")
Politician.create(name: "Robert Menendez", party: "D", multiplier: 14, image: "http://vote-usa.org/Image.aspx?Id=NJMenendezRobert&Col=Headshot100&Def=Headshot100", state: "New Jersey")
Politician.create(name: "Maggie Wood Hassan", party: "D", multiplier: 4, image: "http://vote-usa.org/Image.aspx?Id=NHHassanMaggieWood&Col=Headshot100&Def=Headshot100", state: "New Hampshire")
Politician.create(name: "Jeanne Shaheen", party: "D", multiplier: 4, image: "http://vote-usa.org/Image.aspx?Id=NHShaheenJeanne&Col=Headshot100&Def=Headshot100", state: "New Hampshire")
Politician.create(name: "Catherine Cortez Masto", party: "D", multiplier: 6, image: "http://vote-usa.org/Image.aspx?Id=NVCortezmastoCatherine&Col=Headshot100&Def=Headshot100", state: "Nevada")
Politician.create(name: "Dean Heller", party: "R", multiplier: 6, image: "http://vote-usa.org/Image.aspx?Id=NVHellerDean&Col=Headshot100&Def=Headshot100", state: "Nevada")

# OUTINGS = ["Golf", "Coffee", "Dinner", "Couples Massage", "Wine tasting", "Horseback riding", "Shooting Skeet", "Squash", "Gambling", "Smoking"]



Politician.all.each do |politician|
  politician.outings.create(title: "Golf", description: "Hitting balls with clubs", base_cost: 1300, image_url: "https://s3.amazonaws.com/images.charitybuzz.com/images/70066/original.png?1384591846")
  politician.outings.create(title: "Coffee", description: "Drinking water with beans", base_cost: 100, image_url: "http://media.nj.com/entertainment_impact_dining/photo/coffee-stock-photo-0e8b300f42157b6f.jpg")
  politician.outings.create(title: "Dinner", description: "Eating delicious food and conversating", base_cost: 2500, image_url: "http://crookedcreekguides.com/wp-content/uploads/2016/01/dinner-03.jpg")
  politician.outings.create(title: "Couples Massage", description: "Getting rubbed down by sexy masseuses", base_cost: 3000, image_url: "http://www.hobokenwellnessspa.com/wp-content/uploads/2016/02/MASSAGE-couple.jpg")
  politician.outings.create(title: "Wine Tasting", description: "Drinking old grape juice", base_cost: 2500, image_url: "http://boardinghousechicago.com/dine/wp-content/uploads/2014/12/wine-tasting.jpg")
  politician.outings.create(title: "Horseback Riding", description: "Establishing dominance over inferior species", base_cost: 2001, image_url: "http://flatheadlakelodge.com/wp-content/uploads/2014/05/Horseback_Couple_3840x1600-1440x600.jpg")
  politician.outings.create(title: "Shooting Skeet", description: "It's better than shooting people", base_cost: 1000, image_url: "https://img.washingtonpost.com/wp-apps/imrs.php?src=http://farm9.staticflickr.com/8331/8436110735_5ec05750a2_z.jpg&w=480")
  politician.outings.create(title: "Squash", description: "Hitting balls with racquets in short shorts", base_cost: 1750, image_url: "http://www.expertrain.com/SiteAssets/Images/Should%20you%20be%20playing%20the%20healthiest%20sport/bigstock-Squash-Racket-And-Balls-14153441.jpg")
  politician.outings.create(title: "Gambling", description: "What happens in Vegas, stays in Vegas", base_cost: 10000, image_url: "http://media.coindesk.com/uploads/2014/09/rsz_shutterstock_145623826.jpg")
  politician.outings.create(title: "Smoking", description: "Mmmmm, indubitably", base_cost: 3250, image_url: "http://www.cigarblog.cigarconexion.in/wp-content/uploads/2014/11/The-10-Coolest-Celebrity-Smoking-Cigar-in-Film-and-TV1.jpg")
end